### PR TITLE
Removal of SSH requirements from PP and SD. 

### PR DESCRIPTION
**Pull request by a-kandiah**
Where applicable, references to the SSH Functional Package has been inserted. Changes also have been made to the numbering.

### CODE REVIEW

**Review by plughy2 — COMMENTED** [review]
Shouldn't Section 2 identify the NDcPP is conformant to the Functional Package for Secure Shell (SSH) version 1.0 ?

The Functional Package for SSH allows Curve25519 and Curve448.  The MINT should consider adding corresponding selections and assurance activities in FCS_CKM.1.1 for Curve25519 and/or Curve448.

**Comment by a-kandiah** [comment]
> Shouldn't Section 2 identify the NDcPP is conformant to the Functional Package for Secure Shell (SSH) version 1.0 ?

Page 16 of NDcPP v2.2e already states: _The packages to which exact conformance can be claimed in conjunction with this PP are specified in the ‘Allowed Packages’ list at https://ccusersforum.onlyoffice.com/product/file/doceditor.aspx?fileid=5615628&action=view_. I believe this is the the most elegant way to carry this out. It allows for future reference to other packages (e.g. the NIAP TLS package).
 
> The Functional Package for SSH allows Curve25519 and Curve448. The MINT should consider adding corresponding selections and assurance activities in FCS_CKM.1.1 for Curve25519 and/or Curve448.

I did consider this and I was very close to adding wording for it. However, I couldn't find any NIST test (validation) suites for Edward's curves. The standard for this is specified in the FIPS 186-5 draft. Testing for this is available in only the demo environment of ACVTS. However, it is allowed in a FIPS module by FIPS 140-3 IG C.A.

**Comment by kenji-acumen** [comment]
IMO, (on the short timeframe) it is easier to restrict the crypto selections that may be used, rather than try to define evaluation activities for Curve25519 and Curve448.

PKG_SSH_v1.0 does not specify any management functions so these should still be covered by NDcPP.

PKG_SSH_v1.0 allows "None" to be selected for all auditable events. I believe auditing is required for NDcPP, so the NDcPP needs to specify what audit events from the package are required.

**Comment by a-kandiah** [comment]
I have pushed through a commit which separates out the modules and the packages in Section 2 of the cPP. The SSH package is now listed in the Modules section, along with a condition on cryptographic selections.

**Comment by plughy2** [comment]
To address the issue with the SSH functional package allowing a selection of "None" for all audit events, a suggestion would be to add the following in the NDcPP immediately after Table 5 and before section B.2 Security Audit (FAU):

SSH is not a required component of this cPP. If a TOE implements SSH and the ST author selects SSH in FTP_ITC.1.1, FTP_TRP.1.1/Admin, or FPT_ITT.1.1, the ST should include the Functional Package for Secure Shell (SSH), version 1.0 and include the following requirement in the table below:

image

**Comment by kr15tyk** [comment]
@a-kandiah There are several references to an "Allowed Packages" list that may need rewording.

The [PP_APP_v1.4] uses the following wording, 'If "SSH" is selected, then the TSF shall be validated against the Functional Package for Secure Shell'.

**Comment by a-kandiah** [comment]
> SSH is not a required component of this cPP. If a TOE implements SSH and the ST author selects SSH in FTP_ITC.1.1, FTP_TRP.1.1/Admin, or FPT_ITT.1.1, the ST should include the Functional Package for Secure Shell (SSH), version 1.0

I agree with this.

> and include the following requirement in the table below:
> 
> image

However, I don't agree with this part. Section 3.1 of the SSH package already provides for this table. It would essentially be restating it in the cPP.

**Comment by a-kandiah** [comment]
I've pushed through commits in responses to the comments above. Please take some time to review them. Thanks!

**Comment by kr15tyk** [comment]
@plughy2 and @ConanHoye please let us know if you have time to review the recent changes to this PR.

**Review by ConanHoye — APPROVED** [review]

**Review by plughy2 — APPROVED** [review]

**Pull request merged**
